#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# user is expected by the systemd service file and `/opt/<user>` is its working directory,
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-network-monitor

# Working folder.
if [ -d "/opt/miden-network-monitor" ]
then
    echo "Directory /opt/miden-network-monitor exists."
else
    mkdir -p /opt/miden-network-monitor
fi
sudo chown -R miden-network-monitor /opt/miden-network-monitor

# Configuration folder
if [ -d "/etc/opt/miden-network-monitor" ]
then
    echo "Directory /etc/opt/miden-network-monitor exists."
else
    mkdir -p /etc/opt/miden-network-monitor
fi
sudo chown -R miden-network-monitor /etc/opt/miden-network-monitor

sudo systemctl daemon-reload
